Feature 랜딩페이지 UI구현 #12
codeit-team-1/Linkbrary pull request #27
Opened 2024-09-02 09:14 UTC by youmdang

# 작업분류

- [ ] 버그 수정
- [x] 신규 기능
- [ ] 리팩토링
- [ ] 기타

# 작업개요

- 랜딩 페이지 UI 구현
- 랜딩 페이지 애니메이션 구현

# 작업 상세 내용

- 네비바, 푸터 컴포넌트
- swiper과 aos 라이브러리와 keyframes 사용하여 애니메이션 적용

- 헤더
![스크린샷 2024-09-02 오후 6 08 50](https://github.com/user-attachments/assets/dc59a51f-892e-4528-bae5-b74c178692ce)
![스크린샷 2024-09-02 오후 6 11 15](https://github.com/user-attachments/assets/5b9f9900-bd35-4657-878a-88e3fb0ccb61)

- 푸터
![스크린샷 2024-09-02 오후 6 09 01](https://github.com/user-attachments/assets/5f9bce55-e173-435c-9acb-330c650aefe6)

- 랜딩 페이지
![스크린샷 2024-09-02 오후 6 06 21](https://github.com/user-attachments/assets/3381797a-5566-4a01-b1fc-ebdf8a95fc45)
![스크린샷 2024-09-02 오후 6 07 36](https://github.com/user-attachments/assets/f752e149-8d42-4e1e-99cd-c8544a25bb55)
![스크린샷 2024-09-02 오후 6 08 10](https://github.com/user-attachments/assets/279b1353-70fc-4d58-b74d-61dd4bd703df)

# 리뷰 요구사항
- 검토 부탁드립니다.

# 기타

- Closes #12

2024-09-02 09:54 UTC, L1m3Kun requested changes
eslint로 인해서 build 시에 에러가 나서, 해당 파일 확인부탁드립니다 😄

![스크린샷 2024-09-02 오후 6 52 59](https://github.com/user-attachments/assets/0e2cc01d-87cc-40a0-bebc-45958782b05c)

2024-09-02 09:54 UTC, L1m3Kun commented on src/pages/_app.tsx
> +  );
회원가입이나 로그인 페이지 같은 footer와 navigation 바가 필요없는 경우는 어떻게하면 좋을까요?

2024-09-02 09:54 UTC, L1m3Kun commented on src/styles/landingEffect.css
tailwindcss 사용과 별개로 css 파일을 사용하신 이유가 있을까요?

2024-09-02 09:54 UTC, L1m3Kun commented on tailwind.config.ts
> +          'linear-gradient(to right, #7DD4EB 0%, #9AB8D6 100%)',
color01과 같은 네이밍보다 yellow-to-green과 같은 이름은 어떠신가요?

처음에 제가 네이밍할 땐 하나만 필요한 줄 알고 gradient-color라고 네이밍했는데,
여러개일 경우에는 어떤색인지 이름만 보고 알기 힘들 수도 있겠네요 😄

2024-09-02 09:54 UTC, L1m3Kun commented on tailwind.config.ts
> +        'card-image': 'url("../assets/images/landingCard3-1.png")',
url 경로 확인 부탁드립니다. 😄

2024-09-02 09:58 UTC, youmdang commented on src/pages/_app.tsx
> +  );
이 부분은 url경로가 로그인이나 회원가입이면 헤더나 푸터가 노출이 안되도록 하는걸로 생각중입니다!

2024-09-02 10:00 UTC, L1m3Kun commented on src/pages/_app.tsx
> +  );
그럼 전체 route를 관리하는 파일을 만들까요?
authorize 관련해서도 인가하는 페이지랑 login페이지 리디렉팅 설정할 때도 필요할 것 같아서요!
파일하나에서 관리하면 편할 것 같아요!

2024-09-02 10:03 UTC, youmdang commented on src/styles/landingEffect.css
애니메이션 구현 확인을 위해 간단하게 css로 먼저 구현 상태여서 px을 rem으로 수정할 때 같이 애니메이션을 tailwindconfig에 추가해 보도록 하겠습니다!

2024-09-02 10:04 UTC, youmdang commented on tailwind.config.ts
> +          'linear-gradient(to right, #7DD4EB 0%, #9AB8D6 100%)',
넵 말씀해주신 네이밍이 더 좋을것 같네요 수정해보겠습니다!

2024-09-02 10:05 UTC, L1m3Kun commented on src/styles/landingEffect.css
이런 내용을 pr사항에 넣어주시면 편할 것 같아요! 😄

2024-09-02 10:06 UTC, youmdang commented on tailwind.config.ts
> +        'card-image': 'url("../assets/images/landingCard3-1.png")',
배경이미지에 사용하기 위해서 작성하긴 한건데 경로가 잘 못 된걸까요?

2024-09-02 10:12 UTC, youmdang commented on src/pages/_app.tsx
> +  );
저는 기존에 router.pathname을 사용해서 경로가 로그인이랑 회원가입이면 안보이게 하는 코드를 작성 하려고 했는데 성구님이 말씀하신 내용은 이것도 포함해서 다른 페이지에서도 사용될 부분을 하나의 파일로 만들자는 말씀이신거죠?

2024-09-02 10:13 UTC, youmdang commented
> eslint로 인해서 build 시에 에러가 나서, 해당 파일 확인부탁드립니다 😄
> 
> 
> 
> ![스크린샷 2024-09-02 오후 6 52 59](https://github.com/user-attachments/assets/0e2cc01d-87cc-40a0-bebc-45958782b05c)
> 
> 

넵 해당부분 확인하여 수정해보겠습니다!

2024-09-02 10:14 UTC, L1m3Kun commented on src/pages/_app.tsx
> +  );
전체 라우터 네임을 하나의 객체로 관리해서 enum처럼 사용하는 걸 말씀드리려고 했어요!

그래서 router.pathname이 객체 내에서 non-header과 같은 속성을 가지고 있으면 적용하지 않는 방식을 생각했습니다

2024-09-02 10:16 UTC, L1m3Kun commented on tailwind.config.ts
> +        'card-image': 'url("../assets/images/landingCard3-1.png")',
해당 내용이 적용될 때 기준으로 적용되는 것 같은데,
메인 페이지가 아닌 다른 곳에서 사용하려고 작성되면 이미지가 깨져보일 수 있어보여요!

절대경로를 사용해보시는건 어떠신가요?

2024-09-02 10:19 UTC, youmdang commented on src/pages/_app.tsx
> +  );
아 이해했습니다! 그게 좋을 것 같네요
말씀해주신 부분 추가해 보겠습니다!

2024-09-03 01:14 UTC, ojm51 reviewed
고생하셨습니다👍 빌드 에러 수정한 다음에 머지하면 될 것 같아요!

2024-09-03 01:14 UTC, ojm51 commented on src/components/layout/Footer.tsx
> +          </li>
하나의 `<li>`에 들어가는 내용들을 객체 배열로 만들어서 map으로 뿌려주는 방법도 있을 거 같아용!
```javascript
const snsList = [
  {
    id: 1,
    link: '/',
    image: trashIcon,
    alt: '페이스북 아이콘',
  },
...
];

...

<ul>
  {menuList.map((snsList) => (
    <li key={snsList.id}>
      <Link href={snsList.id}>
        <Image
          width={20}
          height={20}
          src={snsList.image}
          alt={snsList.alt}
         />
      </Link>
    </li>
  ))}
</ul>
```

2024-09-03 05:54 UTC, me92years approved these changes

2024-09-03 05:55 UTC, me92years approved these changes

2024-09-03 08:36 UTC, merged