Feature 링크 리팩토링 #52
codeit-team-1/Linkbrary pull request #85
Opened 2024-09-17 01:26 UTC by ojm51

# 작업분류

- [ ] 버그 수정
- [ ] 신규 기능
- [ ] 리팩토링
- [ ] 기타

# 작업개요

- 링크 페이지 관련 리팩토링

# 작업 상세 내용

- 커스텀 훅 생성
- 폴더 리스트 중복 요청 수정
- 문구 수정

# 리뷰 요구사항

- 확인 부탁드립니다!

# 기타

- close #52

2024-09-17 08:19 UTC, youmdang approved these changes
리팩토링 고생하셨습니다!
충돌 나는 부분만 해결하면 될 것 같아요!

2024-09-17 12:44 UTC, L1m3Kun approved these changes
👍

2024-09-17 12:52 UTC, L1m3Kun requested changes
추석에도 개발이라니 고생많으셨습니다!

2024-09-17 12:52 UTC, L1m3Kun commented on src/lib/context/useFolderHandler.ts
> +  };
default value 같은 경우에는 함수 밖에서 상수형태로 선언하는게 더 좋다고들 하더라구요!😄

2024-09-17 12:52 UTC, L1m3Kun commented on src/lib/context/useFolderHandler.ts
> +      setFolderList(data);
다른 폴더에 링클르 추가하고 `전체` 폴더를 선택하면 전체 데이터가 stale한 상태로 남아있고 새로운 데이터를 가져오지 않더라구요! 
확인 부탁드려도 될까요??

2024-09-18 06:27 UTC, L1m3Kun commented on src/lib/context/useFolderHandler.ts
> +      setFolderList(data);
해결했습니다

2024-09-18 12:14 UTC, merged